/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/cyber_warrior.glb -T -o app/_components/CyberWarrior.jsx 
Files: public/models/cyber_warrior.glb [112.07MB] > /home/farazhaider/faraz/CODE/18. Projects/modern-protfolio/app/_components/cyber_warrior-transformed.glb [11.83MB] (89%)
Author: Jiaxing (https://sketchfab.com/saitoyang)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cyber-warrior-513c541b1508444eb30e62656e97e621
Title: Cyber Warrior
*/

import React, { useMemo } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  // Use the highly optimized, 10x smaller transformed model
  const { scene } = useGLTF('/models/cyber_warrior-transformed.glb')
  
  // High-performance scene-graph optimization run once on load
  useMemo(() => {
    scene.traverse((node) => {
      if (node.isMesh) {
        // 1. Disable all expensive real-time shadow calculations
        node.castShadow = false;
        node.receiveShadow = false;
        
        // 2. Freeze local transformation matrices (saves massive CPU overhead in render loop)
        node.matrixAutoUpdate = false;
        node.updateMatrix();
        
        // 3. Optimize shader material properties
        if (node.material) {
          node.material.precision = "mediump"; // Lower shader complexity
          if (node.material.roughness !== undefined) {
            node.material.roughness = Math.max(node.material.roughness, 0.4); // Simplify reflection math
          }
        }
      }
    });
  }, [scene]);
  
  return (
    <group {...props} dispose={null}>
      {/* <primitive> will render all meshes contained in the GLB scene */}
      <primitive object={scene} />
    </group>
  )
}

useGLTF.preload('/models/cyber_warrior-transformed.glb')
